apiVersion: v1
kind: Service
metadata:
  name: varnish
  labels:
    app: drupal
    tier: nginx-fpm
    environment: dev
spec:
  selector:
    app: drupal
    tier: nginx-fpm
    environment: dev
  type: NodePort
  ports:
  - port: 80
    targetPort: 6081
    nodePort: 31086
    protocol: TCP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: varnish
  labels:
    app: drupal
    tier: nginx-fpm
    environment: dev
spec:
  selector:
    matchLabels:
      app: drupal
      tier: nginx-fpm
      environment: dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
        tier: nginx-fpm
        environment: dev
    spec:
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
      - name: regsecret
      containers:
      - image: "dragosdumi/mysite-varnish:latest"
        name: varnish
        env:
        - name: VARNISH_SECRET
          value: secret
        - name: VARNISH_BACKEND_HOST
          value: nginx
        - name: VARNISH_BACKEND_PORT
          value: "80"
        ports:
        - containerPort: 6081
